FROM ubuntu:22.04
MAINTAINER ntop.org

RUN apt-get update && \
    apt-get -y -q install wget lsb-release gnupg libelf1 && \
    wget -q http://apt.ntop.org/22.04/all/apt-ntop.deb && \
    dpkg -i apt-ntop.deb && \
    apt-get clean all

RUN apt-get update && \
    echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get -y install ntap
    
RUN echo '#!/bin/bash\nntap_remote "$@" $NTOP_CONFIG' > /run.sh && \
    chmod +x /run.sh

ENTRYPOINT ["/run.sh"]
