FROM ubuntu:24.04
MAINTAINER ntop.org

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y -q install wget lsb-release gnupg libelf1 && \
    wget -q https://packages.ntop.org/apt/24.04/all/apt-ntop.deb && \
    dpkg -i apt-ntop.deb && \
    apt-get clean all

RUN apt-get update && \
    apt-get -y install nprobe

RUN echo '#!/bin/bash\nnprobe "$@" $NTOP_CONFIG' > /run.sh && \
    chmod +x /run.sh

ENTRYPOINT ["/run.sh"]
