FROM ubuntu:18.04
MAINTAINER ntop.org

RUN apt-get update && \
    apt-get -y -q install wget lsb-release gnupg && \
    wget -q http://apt.ntop.org/16.04/all/apt-ntop.deb && \
    dpkg -i apt-ntop.deb && \
    apt-get clean all && \
    apt-get update && \
    apt-get -y install pfring && \
    echo '#!/bin/bash\nset -e\nexec "$@"' > /run.sh && \
    chmod +x /run.sh

ENTRYPOINT ["/run.sh"]

