FROM ubuntu:24.04
MAINTAINER ntop.org

RUN apt-get update && \
    apt-get -y -q install wget lsb-release gnupg libelf1 && \
    wget -q https://packages.ntop.org/apt-stable/24.04/all/apt-ntop-stable.deb && \
    dpkg -i apt-ntop-stable.deb && \
    apt-get clean all

RUN apt-get update && \
    apt-get -y install cento

RUN echo '#!/bin/bash\ncento "$@" $NTOP_CONFIG' > /run.sh && \
    chmod +x /run.sh

ENTRYPOINT ["/run.sh"]
